# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        image: node:8.11.2
        name: Deploy
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install -g gulp
          - gulp build   
        artifacts:
          - build/**
    - step:
        # set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables
        name: Deploy to S3
        deployment: staging   # set to test, staging or production
        # trigger: manual  # uncomment to have a manual step
        image: atlassian/pipelines-awscli
        script:
          - cd build && ls
          - aws s3 sync --exclude ".vscode/*" --exclude ".git/*" --delete . s3://portnof.com.ua
