name: Build&Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - name: Setup gulp
      shell: bash
      run: npm install -g gulp
    - name: Install npm packages
      shell: bash
      run: npm install
    - name: Build
      shell: bash
      run: gulp build
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: './build'
        retention-days: 7d
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'   # optional: defaults to us-east-1
        SOURCE_DIR: './build'      # optional: defaults to entire repository